E_Sports_Store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('paypal/', include('paypal.standard.ipn.urls')),
    
    path('', include('product.urls', namespace='product')),
    # path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('after_sale/', include('after_sale.urls'))
]

after_sale/urls.py
from django.urls import path

from .views import (
    ReceiptView,
    HelpView,
)

app_name = 'after_sale'
urlpatterns = [
    path('receipt', ReceiptView.as_view(), name='receipt'),
    path('help', HelpView.as_view(), name='help'),
]

cart/urls.py
from django.urls import path

from .views import(
    CartView,
    ShipView,
    FeedView,
    payment_done,
    payment_canceled,
)

app_name = 'cart'
urlpatterns = [
    path('view/', CartView.as_view(), name='cart'),
    path('shipping/', ShipView.as_view(), name='shipping'),
    path('feedback/', FeedView.as_view(), name='feedback'),
    path('done/', payment_done, name='done'),
    path('canceled/', payment_canceled, name='cancelled'),
]

product/urls.py
from django.urls import path

from .views import(
    GameView,
    TeamView,
    ItemView,
    YTView,
)

app_name = 'product'
urlpatterns = [
    path('', GameView.as_view(), name='index'),
    path('<name>/teams/', TeamView.as_view(), name='team_names'),
    path('<name>/items/', ItemView.as_view(), name='item_names'),
    path('yt/',YTView.as_view(), name='yt'),
]

templates/base.html
<!DOCTYPE html>

<html>

    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'bootstrap/css/mdb.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'bootstrap/css/css/style.min.css' %}" type="text/css">
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

    <head>
        <title>ESS</title>
    </head>

    <body>
        {% include 'navbar.html' %}

        {% for i in "x"|ljust:"2" %}
            <br>
        {% endfor %}

        {% block content %}
            Replace Me
        {% endblock %}
            
    </body>
</html>

templates/navbar.html
<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" target="_blank">
        <strong class="blue-text">ESS</strong>
      </a>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'product:index' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% for each in game_names %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{{each.get_absolute_url}}">{{each.name}}</a>
          </li>
          {% endfor %}
          
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/yt">Live
              <span class="sr-only">(current)</span>
            </a>
          </li>
          
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'after_sale:help' %}">
              <span class="clearfix d-none d-sm-inline-block"> Help </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'cart:feedback' %}">
              <span class="clearfix d-none d-sm-inline-block"> Feedback </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'cart:shipping' %}">
              <span class="clearfix d-none d-sm-inline-block"> Edit Shipping Details </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'cart:cart' %}">
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
              <b><strong class="red-text">{{no_of_items}}</strong></b>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="https://i3dvirtualtour.com/3DTours/ssn">
              <span class="clearfix d-none d-sm-inline-block"> 3D Tour </span>
            </a>
          </li>
        </ul>
          
      </div>

    </div>
  </nav>
  <!-- Navbar -->